cask_args appdir: '/Applications'

# Taps
tap "homebrew/bundle"
tap "homebrew/services"
tap "sass/sass"
tap "teamookla/speedtest"
# End Taps

# Brews
brew "copilot-cli"
brew "docker-compose"
brew "fzf"
brew "gcc"
brew "gh"
brew "git-lfs"
brew "git-secrets"
brew "gnupg"
brew "hey" # tiny program to send some load to a web app
brew "httpd"
brew "imagemagick"
brew "mkcert"
brew "nvm"
brew "openssl"
brew "ruby-install"
brew "sass/sass/sass"
brew "shellcheck"
brew "vim"
brew "zsh"
# End Brews

# Casks
# Tools that you can download via Homebrew but Homebrew doesn’t support them officially
cask "alfred"
cask "anki"
cask "balenaetcher"
cask "calibre"
cask "colour-contrast-analyser"
cask "discord"
cask "docker"
cask "font-hack"
cask "freedom"
cask "google-drive"
cask "gpg-suite-pinentry"
cask "imageoptim"
cask "iterm2"
cask "karabiner-elements"
cask "keycastr"
cask "keysmith"
cask "masscode"
cask "meetingbar"
cask "monitorcontrol"
cask "obsidian"
cask "send-to-kindle"
cask "setapp"
cask "signal"
cask "spotify"
cask "steam"
# End Casks

#####

## Apps that come pre-installed on GitHub devices (or via self-serve):
# brew "git"
# brew "go"
# cask "1password
# cask "1password/tap/1password-cli"
# cask "firefox
# cask "google-chrome
# cask "microsoft-teams
# cask "slack
# cask "visual-studio-code"
# cask "zoom"

## no longer supported at GH:
# cask "notion"
# cask "postman"

## Apps that I no longer use, but maybe will revisit in the future:
# brew "1password-cli"
# brew "act"
# brew "chruby"
# brew "circleci"
# brew "composer"
# brew "deno"
# brew "gmailctl"
# brew "mysql-client"
# brew "php", restart_service: true
# brew "postgresql"
# brew "switchaudio-osx"
# brew "tmux"
# brew "watchman"
# brew "yarn"
# brew "youtube-dl"
# cask "dropbox-capture"
# cask "expressions"
# cask "kdenlive"
# cask "switchhosts"
# cask "vivaldi"
# cask "xbar"
# tap "dart-lang/dart"
# tap "heroku/brew"
# tap "oven-sh/bun"
# tap "thoughtbot/formulae"

## Other:
# brew "nvm" => install using zsh-nvm plugin
