#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")"/..

# Run Homebrew through the Brewfile (exclude if not on a mac)
# Todo: Seperate Mac Specific apps into a seperate Brewfile so I can use this in Linux
if [[ $OSTYPE == 'darwin'* ]]; then
	echo "› brew bundle"
	brew bundle --file ~/.dotfiles/homebrew/Brewfile
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
